all:
	gcc mySigHandler.c -Wall -m32 -std=gnu99 -o mySigHandler
	gcc sendsig.c -Wall -m32 -std=gnu99 -o sendsig
	gcc division.c -Wall -m32 -std=gnu99 -o division

clean:
	rm -rf mySigHandler sendsig division